const spanishVocabData = {
  A1: {
    "問候基礎": [
      { word: "hola", phonetic: "/ˈo.la/", pos: "interj.", gender: null, cn: "你好；哈囉", example: "¡Hola! ¿Cómo estás?", exampleCn: "你好！你怎麼樣？" },
      { word: "adiós", phonetic: "/a.ˈðjos/", pos: "interj.", gender: null, cn: "再見", example: "¡Adiós! Hasta mañana.", exampleCn: "再見！明天見。" },
      { word: "gracias", phonetic: "/ˈɡra.θjas/", pos: "interj.", gender: null, cn: "謝謝", example: "Muchas gracias por tu ayuda.", exampleCn: "非常感謝你的幫助。" },
      { word: "por favor", phonetic: "/por fa.ˈβor/", pos: "phrase", gender: null, cn: "請；麻煩你", example: "Un café, por favor.", exampleCn: "請給我一杯咖啡。" },
      { word: "perdón", phonetic: "/per.ˈðon/", pos: "interj.", gender: null, cn: "對不起；打擾一下", example: "Perdón, ¿dónde está el baño?", exampleCn: "打擾一下，廁所在哪裡？" },
      { word: "sí", phonetic: "/si/", pos: "adv.", gender: null, cn: "是；好", example: "Sí, entiendo.", exampleCn: "是的，我明白。" },
      { word: "no", phonetic: "/no/", pos: "adv.", gender: null, cn: "不；不是", example: "No, no me gusta.", exampleCn: "不，我不喜歡。" },
      { word: "bien", phonetic: "/bjen/", pos: "adv.", gender: null, cn: "好；不錯", example: "Estoy muy bien, gracias.", exampleCn: "我很好，謝謝。" },
      { word: "nombre", phonetic: "/ˈnom.bre/", pos: "n.", gender: "m", cn: "名字", example: "Mi nombre es Carlos.", exampleCn: "我的名字叫卡洛斯。" },
      { word: "señor", phonetic: "/se.ˈɲor/", pos: "n.", gender: "m", cn: "先生", example: "Buenos días, señor García.", exampleCn: "早上好，加西亞先生。" },
      { word: "señora", phonetic: "/se.ˈɲo.ra/", pos: "n.", gender: "f", cn: "女士；太太", example: "La señora López trabaja aquí.", exampleCn: "洛佩斯女士在這裡工作。" },
      { word: "amigo", phonetic: "/a.ˈmi.ɣo/", pos: "n.", gender: "m", cn: "朋友（男）", example: "Él es mi mejor amigo.", exampleCn: "他是我最好的朋友。" },
      { word: "amiga", phonetic: "/a.ˈmi.ɣa/", pos: "n.", gender: "f", cn: "朋友（女）", example: "Ella es mi amiga de la escuela.", exampleCn: "她是我學校的朋友。" },
      { word: "mucho", phonetic: "/ˈmu.tʃo/", pos: "adv.", gender: null, cn: "很；非常；多", example: "Me gusta mucho la música.", exampleCn: "我非常喜歡音樂。" },
      { word: "también", phonetic: "/tam.ˈbjen/", pos: "adv.", gender: null, cn: "也；同樣", example: "Yo también quiero ir.", exampleCn: "我也想去。" },
    ],

    "家庭成員": [
      { word: "familia", phonetic: "/fa.ˈmi.lja/", pos: "n.", gender: "f", cn: "家庭", example: "Mi familia es muy grande.", exampleCn: "我的家庭非常大。" },
      { word: "madre", phonetic: "/ˈma.ðre/", pos: "n.", gender: "f", cn: "媽媽；母親", example: "Mi madre trabaja en un hospital.", exampleCn: "我媽媽在醫院工作。" },
      { word: "padre", phonetic: "/ˈpa.ðre/", pos: "n.", gender: "m", cn: "爸爸；父親", example: "Mi padre cocina muy bien.", exampleCn: "我爸爸做飯做得很好。" },
      { word: "hermano", phonetic: "/er.ˈma.no/", pos: "n.", gender: "m", cn: "兄弟", example: "Tengo un hermano mayor.", exampleCn: "我有一個哥哥。" },
      { word: "hermana", phonetic: "/er.ˈma.na/", pos: "n.", gender: "f", cn: "姐妹", example: "Mi hermana estudia medicina.", exampleCn: "我姐姐學醫學。" },
      { word: "hijo", phonetic: "/ˈi.xo/", pos: "n.", gender: "m", cn: "兒子", example: "Tengo dos hijos.", exampleCn: "我有兩個兒子。" },
      { word: "hija", phonetic: "/ˈi.xa/", pos: "n.", gender: "f", cn: "女兒", example: "Su hija tiene cinco años.", exampleCn: "他的女兒五歲。" },
      { word: "abuelo", phonetic: "/a.ˈβwe.lo/", pos: "n.", gender: "m", cn: "爺爺；外公", example: "Mi abuelo tiene ochenta años.", exampleCn: "我爺爺八十歲了。" },
      { word: "abuela", phonetic: "/a.ˈβwe.la/", pos: "n.", gender: "f", cn: "奶奶；外婆", example: "La abuela hace una paella deliciosa.", exampleCn: "奶奶做的海鮮飯很好吃。" },
      { word: "tío", phonetic: "/ˈti.o/", pos: "n.", gender: "m", cn: "叔叔；舅舅；伯父", example: "Mi tío vive en Madrid.", exampleCn: "我叔叔住在馬德里。" },
      { word: "tía", phonetic: "/ˈti.a/", pos: "n.", gender: "f", cn: "阿姨；姑姑", example: "Mi tía es profesora.", exampleCn: "我阿姨是老師。" },
      { word: "primo", phonetic: "/ˈpri.mo/", pos: "n.", gender: "m", cn: "堂兄弟；表兄弟", example: "Mi primo vive en Barcelona.", exampleCn: "我表弟住在巴塞羅那。" },
      { word: "esposo", phonetic: "/es.ˈpo.so/", pos: "n.", gender: "m", cn: "丈夫", example: "Su esposo es muy simpático.", exampleCn: "她的丈夫非常友善。" },
      { word: "esposa", phonetic: "/es.ˈpo.sa/", pos: "n.", gender: "f", cn: "妻子", example: "Mi esposa trabaja en una tienda.", exampleCn: "我妻子在一家商店工作。" },
      { word: "bebé", phonetic: "/be.ˈβe/", pos: "n.", gender: "m", cn: "嬰兒；寶寶", example: "El bebé duerme todo el día.", exampleCn: "嬰兒整天都在睡覺。" },
    ],

    "數字時間": [
      { word: "uno", phonetic: "/ˈu.no/", pos: "num.", gender: null, cn: "一（1）", example: "Tengo un hermano.", exampleCn: "我有一個兄弟。" },
      { word: "dos", phonetic: "/dos/", pos: "num.", gender: null, cn: "二（2）", example: "Quiero dos cafés, por favor.", exampleCn: "請給我兩杯咖啡。" },
      { word: "cinco", phonetic: "/ˈθin.ko/", pos: "num.", gender: null, cn: "五（5）", example: "Son las cinco de la tarde.", exampleCn: "現在是下午五點。" },
      { word: "diez", phonetic: "/djeθ/", pos: "num.", gender: null, cn: "十（10）", example: "El libro cuesta diez euros.", exampleCn: "這本書十歐元。" },
      { word: "hora", phonetic: "/ˈo.ra/", pos: "n.", gender: "f", cn: "小時；時間", example: "¿Qué hora es?", exampleCn: "現在幾點？" },
      { word: "minuto", phonetic: "/mi.ˈnu.to/", pos: "n.", gender: "m", cn: "分鐘", example: "Espera cinco minutos, por favor.", exampleCn: "請等五分鐘。" },
      { word: "día", phonetic: "/ˈdi.a/", pos: "n.", gender: "m", cn: "天；日子", example: "Hoy es un día bonito.", exampleCn: "今天天氣很好。" },
      { word: "semana", phonetic: "/se.ˈma.na/", pos: "n.", gender: "f", cn: "星期；週", example: "La semana tiene siete días.", exampleCn: "一週有七天。" },
      { word: "mes", phonetic: "/mes/", pos: "n.", gender: "m", cn: "月份；月", example: "El mes de enero es frío.", exampleCn: "一月份很冷。" },
      { word: "año", phonetic: "/ˈa.ɲo/", pos: "n.", gender: "m", cn: "年；歲", example: "Tengo veinte años.", exampleCn: "我二十歲。" },
      { word: "hoy", phonetic: "/oj/", pos: "adv.", gender: null, cn: "今天", example: "Hoy tengo mucho trabajo.", exampleCn: "今天我有很多工作。" },
      { word: "mañana", phonetic: "/ma.ˈɲa.na/", pos: "adv./n.f.", gender: "f", cn: "明天；早上", example: "Nos vemos mañana.", exampleCn: "明天見。" },
      { word: "tarde", phonetic: "/ˈtar.ðe/", pos: "n./adv.", gender: "f", cn: "下午；晚了", example: "Buenas tardes a todos.", exampleCn: "大家下午好。" },
      { word: "noche", phonetic: "/ˈno.tʃe/", pos: "n.", gender: "f", cn: "夜晚；晚上", example: "Buenas noches, hasta mañana.", exampleCn: "晚安，明天見。" },
      { word: "ahora", phonetic: "/a.ˈo.ra/", pos: "adv.", gender: null, cn: "現在；立刻", example: "Ahora no puedo hablar.", exampleCn: "我現在不能說話。" },
    ],

    "顏色形容詞": [
      { word: "rojo", phonetic: "/ˈro.xo/", pos: "adj.", gender: null, cn: "紅色的", example: "Tengo una camiseta roja.", exampleCn: "我有一件紅色的T恤。" },
      { word: "azul", phonetic: "/a.ˈθul/", pos: "adj.", gender: null, cn: "藍色的", example: "El cielo es azul.", exampleCn: "天空是藍色的。" },
      { word: "verde", phonetic: "/ˈber.ðe/", pos: "adj.", gender: null, cn: "綠色的", example: "Me gustan las manzanas verdes.", exampleCn: "我喜歡綠色的蘋果。" },
      { word: "amarillo", phonetic: "/a.ma.ˈri.ʎo/", pos: "adj.", gender: null, cn: "黃色的", example: "El sol es amarillo.", exampleCn: "太陽是黃色的。" },
      { word: "blanco", phonetic: "/ˈblan.ko/", pos: "adj.", gender: null, cn: "白色的", example: "Tengo un gato blanco.", exampleCn: "我有一隻白貓。" },
      { word: "negro", phonetic: "/ˈne.ɣro/", pos: "adj.", gender: null, cn: "黑色的", example: "Lleva un vestido negro.", exampleCn: "她穿著一件黑色的裙子。" },
      { word: "grande", phonetic: "/ˈɡran.de/", pos: "adj.", gender: null, cn: "大的", example: "Vivo en una ciudad grande.", exampleCn: "我住在一個大城市。" },
      { word: "pequeño", phonetic: "/pe.ˈke.ɲo/", pos: "adj.", gender: null, cn: "小的", example: "Mi apartamento es pequeño.", exampleCn: "我的公寓很小。" },
      { word: "bueno", phonetic: "/ˈbwe.no/", pos: "adj.", gender: null, cn: "好的", example: "Es un libro muy bueno.", exampleCn: "這是一本很好的書。" },
      { word: "malo", phonetic: "/ˈma.lo/", pos: "adj.", gender: null, cn: "壞的；不好的", example: "Hoy hay mal tiempo.", exampleCn: "今天天氣不好。" },
      { word: "nuevo", phonetic: "/ˈnwe.βo/", pos: "adj.", gender: null, cn: "新的", example: "Tengo un teléfono nuevo.", exampleCn: "我有一部新手機。" },
      { word: "viejo", phonetic: "/ˈbje.xo/", pos: "adj.", gender: null, cn: "老的；舊的", example: "Este edificio es muy viejo.", exampleCn: "這棟建築物很舊。" },
      { word: "bonito", phonetic: "/bo.ˈni.to/", pos: "adj.", gender: null, cn: "漂亮的；美麗的", example: "Qué vestido tan bonito.", exampleCn: "這件裙子真漂亮。" },
      { word: "alto", phonetic: "/ˈal.to/", pos: "adj.", gender: null, cn: "高的；高大的", example: "Mi hermano es muy alto.", exampleCn: "我哥哥很高。" },
      { word: "feliz", phonetic: "/fe.ˈliθ/", pos: "adj.", gender: null, cn: "快樂的；幸福的", example: "Hoy soy muy feliz.", exampleCn: "今天我非常開心。" },
    ],

    "食物飲料": [
      { word: "agua", phonetic: "/ˈa.ɣwa/", pos: "n.", gender: "f", cn: "水", example: "Quiero un vaso de agua, por favor.", exampleCn: "請給我一杯水。" },
      { word: "leche", phonetic: "/ˈle.tʃe/", pos: "n.", gender: "f", cn: "牛奶", example: "El niño bebe leche cada mañana.", exampleCn: "孩子每天早上喝牛奶。" },
      { word: "pan", phonetic: "/pan/", pos: "n.", gender: "m", cn: "麵包", example: "Me gusta el pan con mantequilla.", exampleCn: "我喜歡吃奶油麵包。" },
      { word: "arroz", phonetic: "/a.ˈroθ/", pos: "n.", gender: "m", cn: "米飯；米", example: "En China comen mucho arroz.", exampleCn: "在中國人們吃很多米飯。" },
      { word: "fruta", phonetic: "/ˈfru.ta/", pos: "n.", gender: "f", cn: "水果", example: "Como fruta todos los días.", exampleCn: "我每天吃水果。" },
      { word: "verdura", phonetic: "/ber.ˈðu.ra/", pos: "n.", gender: "f", cn: "蔬菜", example: "Las verduras son muy saludables.", exampleCn: "蔬菜非常健康。" },
      { word: "carne", phonetic: "/ˈkar.ne/", pos: "n.", gender: "f", cn: "肉", example: "No como carne, soy vegetariano.", exampleCn: "我不吃肉，我是素食者。" },
      { word: "pollo", phonetic: "/ˈpo.ʎo/", pos: "n.", gender: "m", cn: "雞肉；雞", example: "El pollo asado está delicioso.", exampleCn: "烤雞非常好吃。" },
      { word: "pescado", phonetic: "/pes.ˈka.ðo/", pos: "n.", gender: "m", cn: "魚（食用）", example: "En España comen mucho pescado.", exampleCn: "在西班牙人們吃很多魚。" },
      { word: "café", phonetic: "/ka.ˈfe/", pos: "n.", gender: "m", cn: "咖啡", example: "Tomo un café cada mañana.", exampleCn: "我每天早上喝一杯咖啡。" },
      { word: "zumo", phonetic: "/ˈθu.mo/", pos: "n.", gender: "m", cn: "果汁", example: "Quiero un zumo de naranja.", exampleCn: "我想要一杯橙汁。" },
      { word: "cerveza", phonetic: "/θer.ˈβe.θa/", pos: "n.", gender: "f", cn: "啤酒", example: "En el bar pido una cerveza fría.", exampleCn: "在酒吧我點了一杯冰啤酒。" },
      { word: "ensalada", phonetic: "/en.sa.ˈla.ða/", pos: "n.", gender: "f", cn: "沙律；沙拉", example: "La ensalada mixta está muy fresca.", exampleCn: "混合沙拉非常新鮮。" },
      { word: "huevo", phonetic: "/ˈwe.βo/", pos: "n.", gender: "m", cn: "雞蛋", example: "Cada mañana como dos huevos.", exampleCn: "我每天早上吃兩個雞蛋。" },
      { word: "queso", phonetic: "/ˈke.so/", pos: "n.", gender: "m", cn: "芝士；乳酪", example: "El queso manchego es muy famoso.", exampleCn: "曼切戈芝士非常有名。" },
    ],

    "地方場所": [
      { word: "casa", phonetic: "/ˈka.sa/", pos: "n.", gender: "f", cn: "房子；家", example: "Mi casa está cerca del parque.", exampleCn: "我家在公園附近。" },
      { word: "escuela", phonetic: "/es.ˈkwe.la/", pos: "n.", gender: "f", cn: "學校", example: "Los niños van a la escuela.", exampleCn: "孩子們去上學。" },
      { word: "hospital", phonetic: "/os.pi.ˈtal/", pos: "n.", gender: "m", cn: "醫院", example: "El hospital está muy lejos.", exampleCn: "醫院很遠。" },
      { word: "banco", phonetic: "/ˈban.ko/", pos: "n.", gender: "m", cn: "銀行；長凳", example: "Necesito ir al banco hoy.", exampleCn: "我今天需要去銀行。" },
      { word: "supermercado", phonetic: "/su.per.mer.ˈka.ðo/", pos: "n.", gender: "m", cn: "超級市場", example: "Voy al supermercado a comprar comida.", exampleCn: "我去超市買食物。" },
      { word: "restaurante", phonetic: "/res.tau.ˈran.te/", pos: "n.", gender: "m", cn: "餐廳", example: "Cenamos en un restaurante chino.", exampleCn: "我們在中餐廳吃晚飯。" },
      { word: "hotel", phonetic: "/o.ˈtel/", pos: "n.", gender: "m", cn: "酒店；旅館", example: "El hotel está en el centro.", exampleCn: "酒店在市中心。" },
      { word: "ciudad", phonetic: "/θju.ˈðað/", pos: "n.", gender: "f", cn: "城市", example: "Madrid es una ciudad muy bonita.", exampleCn: "馬德里是一座非常漂亮的城市。" },
      { word: "calle", phonetic: "/ˈka.ʎe/", pos: "n.", gender: "f", cn: "街道；街", example: "¿Cuál es tu calle?", exampleCn: "你住在哪條街？" },
      { word: "parque", phonetic: "/ˈpar.ke/", pos: "n.", gender: "m", cn: "公園", example: "Los niños juegan en el parque.", exampleCn: "孩子們在公園玩耍。" },
      { word: "mercado", phonetic: "/mer.ˈka.ðo/", pos: "n.", gender: "m", cn: "市場", example: "En el mercado venden frutas frescas.", exampleCn: "在市場裡賣新鮮水果。" },
      { word: "aeropuerto", phonetic: "/a.e.ro.ˈpwer.to/", pos: "n.", gender: "m", cn: "機場", example: "El aeropuerto está lejos de la ciudad.", exampleCn: "機場離城市很遠。" },
      { word: "farmacia", phonetic: "/far.ˈma.θja/", pos: "n.", gender: "f", cn: "藥房；藥局", example: "La farmacia está en la esquina.", exampleCn: "藥房在轉角處。" },
      { word: "biblioteca", phonetic: "/bi.blio.ˈte.ka/", pos: "n.", gender: "f", cn: "圖書館", example: "Voy a la biblioteca a estudiar.", exampleCn: "我去圖書館學習。" },
      { word: "oficina", phonetic: "/o.fi.ˈθi.na/", pos: "n.", gender: "f", cn: "辦公室", example: "Trabajo en una oficina grande.", exampleCn: "我在一個大辦公室工作。" },
    ],

    "日常物品": [
      { word: "libro", phonetic: "/ˈli.βro/", pos: "n.", gender: "m", cn: "書；書本", example: "Estoy leyendo un libro muy interesante.", exampleCn: "我在讀一本很有趣的書。" },
      { word: "mesa", phonetic: "/ˈme.sa/", pos: "n.", gender: "f", cn: "桌子", example: "La comida está en la mesa.", exampleCn: "食物在桌子上。" },
      { word: "silla", phonetic: "/ˈsi.ʎa/", pos: "n.", gender: "f", cn: "椅子", example: "Siéntate en esa silla.", exampleCn: "坐在那把椅子上。" },
      { word: "cama", phonetic: "/ˈka.ma/", pos: "n.", gender: "f", cn: "床", example: "Me gusta dormir en una cama cómoda.", exampleCn: "我喜歡睡在舒適的床上。" },
      { word: "puerta", phonetic: "/ˈpwer.ta/", pos: "n.", gender: "f", cn: "門", example: "Abre la puerta, por favor.", exampleCn: "請開門。" },
      { word: "ventana", phonetic: "/ben.ˈta.na/", pos: "n.", gender: "f", cn: "窗戶", example: "La ventana está abierta.", exampleCn: "窗戶是開著的。" },
      { word: "teléfono", phonetic: "/te.ˈle.fo.no/", pos: "n.", gender: "m", cn: "電話；手機", example: "¿Cuál es tu número de teléfono?", exampleCn: "你的電話號碼是多少？" },
      { word: "ordenador", phonetic: "/or.ðe.na.ˈðor/", pos: "n.", gender: "m", cn: "電腦（西班牙）", example: "Trabajo con el ordenador todo el día.", exampleCn: "我整天都在用電腦工作。" },
      { word: "bolso", phonetic: "/ˈbol.so/", pos: "n.", gender: "m", cn: "手提包；錢包", example: "Ella lleva un bolso rojo.", exampleCn: "她帶著一個紅色的手提包。" },
      { word: "ropa", phonetic: "/ˈro.pa/", pos: "n.", gender: "f", cn: "衣服；服裝", example: "Necesito comprar ropa nueva.", exampleCn: "我需要買新衣服。" },
      { word: "zapatos", phonetic: "/θa.ˈpa.tos/", pos: "n.", gender: "m", cn: "鞋子", example: "Me gustan estos zapatos negros.", exampleCn: "我喜歡這雙黑色的鞋子。" },
      { word: "llave", phonetic: "/ˈʎa.βe/", pos: "n.", gender: "f", cn: "鑰匙", example: "¿Dónde están mis llaves?", exampleCn: "我的鑰匙在哪裡？" },
      { word: "dinero", phonetic: "/di.ˈne.ro/", pos: "n.", gender: "m", cn: "錢；金錢", example: "No tengo mucho dinero.", exampleCn: "我沒有很多錢。" },
      { word: "reloj", phonetic: "/re.ˈlox/", pos: "n.", gender: "m", cn: "手錶；時鐘", example: "Mi reloj es de oro.", exampleCn: "我的手錶是金的。" },
      { word: "papel", phonetic: "/pa.ˈpel/", pos: "n.", gender: "m", cn: "紙；文件", example: "Necesito un papel y un bolígrafo.", exampleCn: "我需要一張紙和一支筆。" },
    ],

    "基礎動詞": [
      { word: "ser", phonetic: "/ser/", pos: "v.", gender: null, cn: "是（本質）", example: "Soy estudiante.", exampleCn: "我是學生。" },
      { word: "estar", phonetic: "/es.ˈtar/", pos: "v.", gender: null, cn: "是（狀態）；在", example: "Estoy en casa.", exampleCn: "我在家。" },
      { word: "tener", phonetic: "/te.ˈner/", pos: "v.", gender: null, cn: "有；擁有", example: "Tengo dos hermanas.", exampleCn: "我有兩個姐妹。" },
      { word: "hacer", phonetic: "/a.ˈθer/", pos: "v.", gender: null, cn: "做；製作", example: "¿Qué haces hoy?", exampleCn: "你今天做什麼？" },
      { word: "ir", phonetic: "/ir/", pos: "v.", gender: null, cn: "去；前往", example: "Voy al trabajo en metro.", exampleCn: "我坐地鐵去上班。" },
      { word: "venir", phonetic: "/be.ˈnir/", pos: "v.", gender: null, cn: "來；到來", example: "¿Puedes venir mañana?", exampleCn: "你明天能來嗎？" },
      { word: "hablar", phonetic: "/a.ˈβlar/", pos: "v.", gender: null, cn: "說話；講", example: "Hablo español un poco.", exampleCn: "我會說一點西班牙語。" },
      { word: "comer", phonetic: "/ko.ˈmer/", pos: "v.", gender: null, cn: "吃", example: "Como a las dos de la tarde.", exampleCn: "我下午兩點吃飯。" },
      { word: "beber", phonetic: "/be.ˈβer/", pos: "v.", gender: null, cn: "喝", example: "Bebo mucha agua cada día.", exampleCn: "我每天喝很多水。" },
      { word: "vivir", phonetic: "/bi.ˈβir/", pos: "v.", gender: null, cn: "居住；生活", example: "Vivo en Hong Kong.", exampleCn: "我住在香港。" },
      { word: "trabajar", phonetic: "/tra.βa.ˈxar/", pos: "v.", gender: null, cn: "工作", example: "Trabajo en una empresa grande.", exampleCn: "我在一家大公司工作。" },
      { word: "estudiar", phonetic: "/es.tu.ˈðjar/", pos: "v.", gender: null, cn: "學習；讀書", example: "Estudio español dos horas al día.", exampleCn: "我每天學習西班牙語兩個小時。" },
      { word: "querer", phonetic: "/ke.ˈrer/", pos: "v.", gender: null, cn: "想要；愛", example: "Quiero aprender más idiomas.", exampleCn: "我想學更多語言。" },
      { word: "poder", phonetic: "/po.ˈðer/", pos: "v.", gender: null, cn: "能夠；可以", example: "¿Puedes ayudarme, por favor?", exampleCn: "你能幫助我嗎？" },
      { word: "gustar", phonetic: "/ɡus.ˈtar/", pos: "v.", gender: null, cn: "喜歡", example: "Me gusta mucho el chocolate.", exampleCn: "我非常喜歡巧克力。" },
    ],
  },

  A2: {
    "交通旅遊": [
      { word: "avión", phonetic: "/a.ˈβjon/", pos: "n.", gender: "m", cn: "飛機", example: "El avión sale a las ocho.", exampleCn: "飛機八點出發。" },
      { word: "tren", phonetic: "/tren/", pos: "n.", gender: "m", cn: "火車", example: "Voy a Madrid en tren.", exampleCn: "我坐火車去馬德里。" },
      { word: "autobús", phonetic: "/au.to.ˈβus/", pos: "n.", gender: "m", cn: "公共汽車；巴士", example: "El autobús número cinco va al centro.", exampleCn: "五號巴士去市中心。" },
      { word: "metro", phonetic: "/ˈme.tro/", pos: "n.", gender: "m", cn: "地鐵", example: "En Madrid el metro es muy rápido.", exampleCn: "馬德里的地鐵非常快。" },
      { word: "billete", phonetic: "/bi.ˈʎe.te/", pos: "n.", gender: "m", cn: "車票；機票", example: "Necesito comprar un billete de tren.", exampleCn: "我需要買一張火車票。" },
      { word: "pasaporte", phonetic: "/pa.sa.ˈpor.te/", pos: "n.", gender: "m", cn: "護照", example: "No olvides tu pasaporte.", exampleCn: "不要忘記帶護照。" },
      { word: "maleta", phonetic: "/ma.ˈle.ta/", pos: "n.", gender: "f", cn: "行李箱", example: "Mi maleta es muy pesada.", exampleCn: "我的行李箱很重。" },
      { word: "viaje", phonetic: "/ˈbja.xe/", pos: "n.", gender: "m", cn: "旅行；旅程", example: "El viaje a España fue increíble.", exampleCn: "去西班牙的旅行太精彩了。" },
      { word: "turista", phonetic: "/tu.ˈris.ta/", pos: "n.", gender: "m/f", cn: "遊客；旅客", example: "Hay muchos turistas en verano.", exampleCn: "夏天有很多遊客。" },
      { word: "reserva", phonetic: "/re.ˈser.βa/", pos: "n.", gender: "f", cn: "預訂；預約", example: "Tengo una reserva en el hotel.", exampleCn: "我在酒店有預訂。" },
      { word: "vuelo", phonetic: "/ˈbwe.lo/", pos: "n.", gender: "m", cn: "航班；飛行", example: "Mi vuelo sale a medianoche.", exampleCn: "我的航班午夜出發。" },
      { word: "llegada", phonetic: "/ʎe.ˈɣa.ða/", pos: "n.", gender: "f", cn: "到達；抵達", example: "La llegada está prevista para las tres.", exampleCn: "預計三點到達。" },
      { word: "salida", phonetic: "/sa.ˈli.ða/", pos: "n.", gender: "f", cn: "出發；出口", example: "La salida del tren es a las nueve.", exampleCn: "火車九點出發。" },
      { word: "mapa", phonetic: "/ˈma.pa/", pos: "n.", gender: "m", cn: "地圖", example: "Necesito un mapa de la ciudad.", exampleCn: "我需要一張城市地圖。" },
      { word: "dirección", phonetic: "/di.rek.ˈθjon/", pos: "n.", gender: "f", cn: "地址；方向", example: "¿Me puede dar su dirección?", exampleCn: "你能給我你的地址嗎？" },
    ],

    "購物消費": [
      { word: "precio", phonetic: "/ˈpre.θjo/", pos: "n.", gender: "m", cn: "價格；價錢", example: "¿Cuál es el precio de esta camisa?", exampleCn: "這件衬衫的價格是多少？" },
      { word: "tienda", phonetic: "/ˈtjen.da/", pos: "n.", gender: "f", cn: "商店；店舖", example: "Esta tienda vende ropa bonita.", exampleCn: "這家店賣漂亮的衣服。" },
      { word: "descuento", phonetic: "/des.ˈkwen.to/", pos: "n.", gender: "m", cn: "折扣；優惠", example: "Hay un descuento del 20%.", exampleCn: "有八折優惠。" },
      { word: "tarjeta", phonetic: "/tar.ˈxe.ta/", pos: "n.", gender: "f", cn: "信用卡；卡片", example: "¿Puedo pagar con tarjeta?", exampleCn: "我可以用信用卡付款嗎？" },
      { word: "efectivo", phonetic: "/e.fek.ˈti.βo/", pos: "n.", gender: "m", cn: "現金", example: "Solo aceptamos efectivo.", exampleCn: "我們只接受現金。" },
      { word: "talla", phonetic: "/ˈta.ʎa/", pos: "n.", gender: "f", cn: "尺碼；尺寸", example: "¿Qué talla usas?", exampleCn: "你穿什麼尺碼？" },
      { word: "oferta", phonetic: "/o.ˈfer.ta/", pos: "n.", gender: "f", cn: "特價；優惠", example: "Hay una oferta especial hoy.", exampleCn: "今天有特別優惠。" },
      { word: "recibo", phonetic: "/re.ˈθi.βo/", pos: "n.", gender: "m", cn: "收據；收條", example: "¿Me puede dar el recibo?", exampleCn: "你能給我收據嗎？" },
      { word: "regalo", phonetic: "/re.ˈɣa.lo/", pos: "n.", gender: "m", cn: "禮物", example: "Quiero comprar un regalo para mi madre.", exampleCn: "我想為媽媽買一件禮物。" },
      { word: "comprar", phonetic: "/kom.ˈprar/", pos: "v.", gender: null, cn: "買；購買", example: "Voy a comprar pan en la panadería.", exampleCn: "我去麵包店買麵包。" },
      { word: "vender", phonetic: "/ben.ˈder/", pos: "v.", gender: null, cn: "賣；出售", example: "Esta tienda vende libros usados.", exampleCn: "這家店賣二手書。" },
      { word: "pagar", phonetic: "/pa.ˈɣar/", pos: "v.", gender: null, cn: "付款；付錢", example: "¿Dónde puedo pagar?", exampleCn: "我在哪裡可以付款？" },
      { word: "cambio", phonetic: "/ˈkam.bjo/", pos: "n.", gender: "m", cn: "找零；零錢；換匯", example: "¿Tiene cambio de veinte euros?", exampleCn: "你有二十歐元的零錢嗎？" },
      { word: "caro", phonetic: "/ˈka.ro/", pos: "adj.", gender: null, cn: "貴的；昂貴的", example: "Este restaurante es muy caro.", exampleCn: "這家餐廳很貴。" },
      { word: "barato", phonetic: "/ba.ˈra.to/", pos: "adj.", gender: null, cn: "便宜的", example: "Encontré unos zapatos muy baratos.", exampleCn: "我找到了一雙很便宜的鞋子。" },
    ],

    "身體健康": [
      { word: "cabeza", phonetic: "/ka.ˈβe.θa/", pos: "n.", gender: "f", cn: "頭", example: "Me duele la cabeza.", exampleCn: "我頭痛。" },
      { word: "mano", phonetic: "/ˈma.no/", pos: "n.", gender: "f", cn: "手", example: "Lávate las manos antes de comer.", exampleCn: "吃飯前洗手。" },
      { word: "ojo", phonetic: "/ˈo.xo/", pos: "n.", gender: "m", cn: "眼睛", example: "Tiene los ojos azules.", exampleCn: "他有藍色的眼睛。" },
      { word: "nariz", phonetic: "/na.ˈriθ/", pos: "n.", gender: "f", cn: "鼻子", example: "Tengo la nariz tapada.", exampleCn: "我鼻子塞住了。" },
      { word: "dolor", phonetic: "/do.ˈlor/", pos: "n.", gender: "m", cn: "疼痛；痛", example: "Tengo un dolor de estómago.", exampleCn: "我肚子痛。" },
      { word: "fiebre", phonetic: "/ˈfje.βre/", pos: "n.", gender: "f", cn: "發燒；發熱", example: "El niño tiene fiebre alta.", exampleCn: "孩子發高燒。" },
      { word: "medicina", phonetic: "/me.ði.ˈθi.na/", pos: "n.", gender: "f", cn: "藥物；醫學", example: "El médico me recetó una medicina.", exampleCn: "醫生給我開了一種藥。" },
      { word: "médico", phonetic: "/ˈme.ði.ko/", pos: "n.", gender: "m", cn: "醫生", example: "Necesito ver a un médico.", exampleCn: "我需要看醫生。" },
      { word: "enfermedad", phonetic: "/en.fer.me.ˈðað/", pos: "n.", gender: "f", cn: "疾病；病", example: "La gripe es una enfermedad común.", exampleCn: "流感是一種常見的疾病。" },
      { word: "salud", phonetic: "/sa.ˈluð/", pos: "n.", gender: "f", cn: "健康；健康狀況", example: "La salud es lo más importante.", exampleCn: "健康是最重要的。" },
      { word: "cansado", phonetic: "/kan.ˈsa.ðo/", pos: "adj.", gender: null, cn: "疲倦的；累的", example: "Estoy muy cansado después del trabajo.", exampleCn: "工作後我非常疲倦。" },
      { word: "corazón", phonetic: "/ko.ra.ˈθon/", pos: "n.", gender: "m", cn: "心臟；心", example: "El ejercicio es bueno para el corazón.", exampleCn: "運動對心臟有好處。" },
      { word: "sangre", phonetic: "/ˈsan.ɡre/", pos: "n.", gender: "f", cn: "血液；血", example: "El médico analizó mi sangre.", exampleCn: "醫生分析了我的血液。" },
      { word: "alergia", phonetic: "/a.ˈler.xja/", pos: "n.", gender: "f", cn: "過敏", example: "Tengo alergia al polen.", exampleCn: "我對花粉過敏。" },
      { word: "descansar", phonetic: "/des.kan.ˈsar/", pos: "v.", gender: null, cn: "休息", example: "Necesitas descansar más.", exampleCn: "你需要多休息。" },
    ],

    "工作職業": [
      { word: "trabajo", phonetic: "/tra.ˈβa.xo/", pos: "n.", gender: "m", cn: "工作；職業", example: "Mi trabajo es muy interesante.", exampleCn: "我的工作非常有趣。" },
      { word: "empresa", phonetic: "/em.ˈpre.sa/", pos: "n.", gender: "f", cn: "公司；企業", example: "Trabajo en una empresa internacional.", exampleCn: "我在一家國際公司工作。" },
      { word: "jefe", phonetic: "/ˈxe.fe/", pos: "n.", gender: "m", cn: "老闆；上司", example: "Mi jefe es muy exigente.", exampleCn: "我的老闆要求很高。" },
      { word: "sueldo", phonetic: "/ˈswel.ðo/", pos: "n.", gender: "m", cn: "薪水；工資", example: "El sueldo mínimo ha subido.", exampleCn: "最低工資已經上漲了。" },
      { word: "reunión", phonetic: "/reu.ˈnjon/", pos: "n.", gender: "f", cn: "會議", example: "Tengo una reunión a las diez.", exampleCn: "我十點有個會議。" },
      { word: "profesor", phonetic: "/pro.fe.ˈsor/", pos: "n.", gender: "m", cn: "教師；老師", example: "El profesor explica muy bien.", exampleCn: "這位老師解釋得很好。" },
      { word: "cocinero", phonetic: "/ko.θi.ˈne.ro/", pos: "n.", gender: "m", cn: "廚師", example: "El cocinero prepara platos deliciosos.", exampleCn: "廚師準備美味的菜餚。" },
      { word: "abogado", phonetic: "/a.βo.ˈɣa.ðo/", pos: "n.", gender: "m", cn: "律師", example: "Necesito hablar con un abogado.", exampleCn: "我需要和律師談談。" },
      { word: "ingeniero", phonetic: "/in.xe.ˈnje.ro/", pos: "n.", gender: "m", cn: "工程師", example: "Mi hermano es ingeniero informático.", exampleCn: "我哥哥是電腦工程師。" },
      { word: "contrato", phonetic: "/kon.ˈtra.to/", pos: "n.", gender: "m", cn: "合同；合約", example: "Firmé el contrato de trabajo.", exampleCn: "我簽了工作合同。" },
      { word: "entrevista", phonetic: "/en.tre.ˈβis.ta/", pos: "n.", gender: "f", cn: "面試；採訪", example: "Tengo una entrevista mañana.", exampleCn: "我明天有面試。" },
      { word: "desempleo", phonetic: "/des.em.ˈple.o/", pos: "n.", gender: "m", cn: "失業；失業率", example: "El desempleo juvenil es un problema.", exampleCn: "青年失業是一個問題。" },
      { word: "experiencia", phonetic: "/eks.pe.ˈrjen.θja/", pos: "n.", gender: "f", cn: "經驗；經歷", example: "Necesitas más experiencia laboral.", exampleCn: "你需要更多工作經驗。" },
      { word: "horario", phonetic: "/o.ˈra.rjo/", pos: "n.", gender: "m", cn: "時間表；時刻表", example: "Mi horario de trabajo es flexible.", exampleCn: "我的工作時間表很靈活。" },
      { word: "jubilación", phonetic: "/xu.βi.la.ˈθjon/", pos: "n.", gender: "f", cn: "退休；養老金", example: "Mi padre se acerca a la jubilación.", exampleCn: "我父親快要退休了。" },
    ],

    "天氣自然": [
      { word: "sol", phonetic: "/sol/", pos: "n.", gender: "m", cn: "太陽；陽光", example: "Hace mucho sol hoy.", exampleCn: "今天陽光很好。" },
      { word: "lluvia", phonetic: "/ˈʎu.βja/", pos: "n.", gender: "f", cn: "雨；雨水", example: "La lluvia empieza por la tarde.", exampleCn: "下午開始下雨。" },
      { word: "viento", phonetic: "/ˈbjen.to/", pos: "n.", gender: "m", cn: "風", example: "Hace mucho viento hoy.", exampleCn: "今天風很大。" },
      { word: "nieve", phonetic: "/ˈnje.βe/", pos: "n.", gender: "f", cn: "雪", example: "En enero cae mucha nieve.", exampleCn: "一月份下了很多雪。" },
      { word: "temperatura", phonetic: "/tem.pe.ra.ˈtu.ra/", pos: "n.", gender: "f", cn: "溫度；氣溫", example: "La temperatura hoy es de 25 grados.", exampleCn: "今天氣溫是25度。" },
      { word: "calor", phonetic: "/ka.ˈlor/", pos: "n.", gender: "m", cn: "熱；炎熱", example: "En verano hace mucho calor.", exampleCn: "夏天非常炎熱。" },
      { word: "frío", phonetic: "/ˈfri.o/", pos: "n./adj.", gender: "m", cn: "冷；寒冷", example: "Tengo frío, ¿puedes cerrar la ventana?", exampleCn: "我很冷，你能關窗嗎？" },
      { word: "nube", phonetic: "/ˈnu.βe/", pos: "n.", gender: "f", cn: "雲；雲朵", example: "El cielo está lleno de nubes.", exampleCn: "天空佈滿了雲。" },
      { word: "tormenta", phonetic: "/tor.ˈmen.ta/", pos: "n.", gender: "f", pos: "n.", cn: "風暴；暴風雨", example: "Hay una tormenta esta noche.", exampleCn: "今晚有暴風雨。" },
      { word: "río", phonetic: "/ˈri.o/", pos: "n.", gender: "m", cn: "河流；河", example: "El río Ebro es muy largo.", exampleCn: "埃布羅河很長。" },
      { word: "montaña", phonetic: "/mon.ˈta.ɲa/", pos: "n.", gender: "f", cn: "山；山脈", example: "Hay nieve en la montaña.", exampleCn: "山上有雪。" },
      { word: "mar", phonetic: "/mar/", pos: "n.", gender: "m", cn: "海；大海", example: "El mar Mediterráneo es muy azul.", exampleCn: "地中海非常藍。" },
      { word: "bosque", phonetic: "/ˈbos.ke/", pos: "n.", gender: "m", cn: "森林；樹林", example: "Hay muchos animales en el bosque.", exampleCn: "森林裡有很多動物。" },
      { word: "flor", phonetic: "/flor/", pos: "n.", gender: "f", cn: "花；花朵", example: "Las flores del jardín son preciosas.", exampleCn: "花園裡的花非常美麗。" },
      { word: "animal", phonetic: "/a.ni.ˈmal/", pos: "n.", gender: "m", cn: "動物", example: "Mi animal favorito es el perro.", exampleCn: "我最喜歡的動物是狗。" },
    ],

    "娛樂愛好": [
      { word: "música", phonetic: "/ˈmu.si.ka/", pos: "n.", gender: "f", cn: "音樂", example: "Me encanta escuchar música clásica.", exampleCn: "我非常喜歡聽古典音樂。" },
      { word: "película", phonetic: "/pe.ˈli.ku.la/", pos: "n.", gender: "f", cn: "電影", example: "¿Quieres ver una película esta noche?", exampleCn: "你今晚想看電影嗎？" },
      { word: "deporte", phonetic: "/de.ˈpor.te/", pos: "n.", gender: "m", cn: "運動；體育", example: "El fútbol es el deporte más popular.", exampleCn: "足球是最受歡迎的運動。" },
      { word: "fútbol", phonetic: "/ˈfut.βol/", pos: "n.", gender: "m", cn: "足球", example: "Juego al fútbol los sábados.", exampleCn: "我週六踢足球。" },
      { word: "bailar", phonetic: "/bai.ˈlar/", pos: "v.", gender: null, cn: "跳舞", example: "Me encanta bailar salsa.", exampleCn: "我非常喜歡跳薩爾薩舞。" },
      { word: "cantar", phonetic: "/kan.ˈtar/", pos: "v.", gender: null, cn: "唱歌", example: "Mi hermana canta muy bien.", exampleCn: "我姐姐唱歌唱得很好。" },
      { word: "leer", phonetic: "/le.ˈer/", pos: "v.", gender: null, cn: "閱讀；看書", example: "Leo una hora antes de dormir.", exampleCn: "我睡前讀一個小時的書。" },
      { word: "cocinar", phonetic: "/ko.θi.ˈnar/", pos: "v.", gender: null, cn: "做飯；烹飪", example: "Me gusta cocinar platos nuevos.", exampleCn: "我喜歡做新菜餚。" },
      { word: "fotografía", phonetic: "/fo.to.ɣra.ˈfi.a/", pos: "n.", gender: "f", cn: "攝影；照片", example: "La fotografía es mi pasatiempo favorito.", exampleCn: "攝影是我最喜歡的愛好。" },
      { word: "concierto", phonetic: "/kon.ˈθjer.to/", pos: "n.", gender: "m", cn: "音樂會；演唱會", example: "Voy a un concierto este fin de semana.", exampleCn: "我這個週末去看音樂會。" },
      { word: "teatro", phonetic: "/te.ˈa.tro/", pos: "n.", gender: "m", cn: "劇場；戲劇", example: "Me gusta ir al teatro.", exampleCn: "我喜歡去看戲劇。" },
      { word: "partido", phonetic: "/par.ˈti.ðo/", pos: "n.", gender: "m", cn: "比賽；球賽", example: "El partido de fútbol empieza a las ocho.", exampleCn: "足球比賽八點開始。" },
      { word: "gimnasio", phonetic: "/xim.ˈna.sjo/", pos: "n.", gender: "m", cn: "健身房；體育館", example: "Voy al gimnasio tres veces por semana.", exampleCn: "我每週去健身房三次。" },
      { word: "videojuego", phonetic: "/bi.ðe.o.ˈxwe.ɣo/", pos: "n.", gender: "m", cn: "電子遊戲", example: "Mi hermano juega videojuegos todo el día.", exampleCn: "我兄弟整天都在玩電子遊戲。" },
      { word: "pasatiempo", phonetic: "/pa.sa.ˈtjem.po/", pos: "n.", gender: "m", cn: "愛好；消遣", example: "¿Cuál es tu pasatiempo favorito?", exampleCn: "你最喜歡的愛好是什麼？" },
    ],

    "感情描述": [
      { word: "feliz", phonetic: "/fe.ˈliθ/", pos: "adj.", gender: null, cn: "開心的；快樂的", example: "Estoy muy feliz hoy.", exampleCn: "我今天很開心。" },
      { word: "triste", phonetic: "/ˈtris.te/", pos: "adj.", gender: null, cn: "悲傷的；難過的", example: "Estoy triste porque llueve.", exampleCn: "我因為下雨而難過。" },
      { word: "enfadado", phonetic: "/en.fa.ˈða.ðo/", pos: "adj.", gender: null, cn: "生氣的；憤怒的", example: "Mi jefe está muy enfadado.", exampleCn: "我老闆非常生氣。" },
      { word: "nervioso", phonetic: "/ner.ˈβjo.so/", pos: "adj.", gender: null, cn: "緊張的", example: "Estoy nervioso antes del examen.", exampleCn: "我在考試前很緊張。" },
      { word: "emocionado", phonetic: "/e.mo.θjo.ˈna.ðo/", pos: "adj.", gender: null, cn: "興奮的；激動的", example: "Estoy emocionado por el viaje.", exampleCn: "我因為旅行而感到興奮。" },
      { word: "sorprendido", phonetic: "/sor.pren.ˈdi.ðo/", pos: "adj.", gender: null, cn: "驚訝的；意外的", example: "Estoy sorprendido por tu noticia.", exampleCn: "你的消息讓我很驚訝。" },
      { word: "preocupado", phonetic: "/pre.o.ku.ˈpa.ðo/", pos: "adj.", gender: null, cn: "擔心的；憂慮的", example: "Estoy preocupado por mi examen.", exampleCn: "我擔心我的考試。" },
      { word: "tranquilo", phonetic: "/tran.ˈki.lo/", pos: "adj.", gender: null, cn: "平靜的；安靜的", example: "Necesito un lugar tranquilo.", exampleCn: "我需要一個安靜的地方。" },
      { word: "aburrido", phonetic: "/a.βu.ˈri.ðo/", pos: "adj.", gender: null, cn: "無聊的；厭倦的", example: "La clase de matemáticas es muy aburrida.", exampleCn: "數學課很無聊。" },
      { word: "orgulloso", phonetic: "/or.ɣu.ˈʎo.so/", pos: "adj.", gender: null, cn: "驕傲的；自豪的", example: "Estoy muy orgulloso de ti.", exampleCn: "我非常為你自豪。" },
      { word: "sentimiento", phonetic: "/sen.ti.ˈmjen.to/", pos: "n.", gender: "m", cn: "感情；感覺", example: "Es difícil expresar mis sentimientos.", exampleCn: "很難表達我的感情。" },
      { word: "amor", phonetic: "/a.ˈmor/", pos: "n.", gender: "m", cn: "愛；愛情", example: "El amor es lo más bonito.", exampleCn: "愛是最美好的事情。" },
      { word: "amistad", phonetic: "/a.mis.ˈtað/", pos: "n.", gender: "f", cn: "友誼；友情", example: "La amistad es muy importante.", exampleCn: "友誼非常重要。" },
      { word: "confianza", phonetic: "/kon.ˈfjan.θa/", pos: "n.", gender: "f", cn: "信任；信心", example: "La confianza es la base de una relación.", exampleCn: "信任是關係的基礎。" },
      { word: "esperanza", phonetic: "/es.pe.ˈran.θa/", pos: "n.", gender: "f", cn: "希望；期望", example: "Nunca pierdas la esperanza.", exampleCn: "永遠不要放棄希望。" },
    ],

    "社會城市": [
      { word: "gobierno", phonetic: "/ɡo.ˈβjer.no/", pos: "n.", gender: "m", cn: "政府", example: "El gobierno aprobó una nueva ley.", exampleCn: "政府批准了一項新法律。" },
      { word: "ley", phonetic: "/lej/", pos: "n.", gender: "f", cn: "法律；法令", example: "Todos debemos respetar la ley.", exampleCn: "我們所有人都應該遵守法律。" },
      { word: "ciudadano", phonetic: "/θju.ða.ˈða.no/", pos: "n.", gender: "m", cn: "公民；市民", example: "Todos los ciudadanos tienen derechos.", exampleCn: "所有公民都有權利。" },
      { word: "vecino", phonetic: "/be.ˈθi.no/", pos: "n.", gender: "m", cn: "鄰居", example: "Mi vecino es muy simpático.", exampleCn: "我的鄰居非常友善。" },
      { word: "barrio", phonetic: "/ˈba.rjo/", pos: "n.", gender: "m", cn: "社區；街區", example: "Vivo en un barrio tranquilo.", exampleCn: "我住在一個安靜的社區。" },
      { word: "transporte", phonetic: "/trans.ˈpor.te/", pos: "n.", gender: "m", cn: "交通；運輸", example: "El transporte público es muy eficiente.", exampleCn: "公共交通非常高效。" },
      { word: "contaminación", phonetic: "/kon.ta.mi.na.ˈθjon/", pos: "n.", gender: "f", cn: "污染", example: "La contaminación del aire es un problema.", exampleCn: "空氣污染是個問題。" },
      { word: "problema", phonetic: "/pro.ˈβle.ma/", pos: "n.", gender: "m", cn: "問題；難題", example: "Tenemos un problema serio.", exampleCn: "我們有個嚴重的問題。" },
      { word: "solución", phonetic: "/so.lu.ˈθjon/", pos: "n.", gender: "f", cn: "解決方案；答案", example: "Necesitamos encontrar una solución.", exampleCn: "我們需要找到解決方案。" },
      { word: "noticia", phonetic: "/no.ˈti.θja/", pos: "n.", gender: "f", cn: "新聞；消息", example: "He escuchado una noticia importante.", exampleCn: "我聽到了一個重要的消息。" },
      { word: "periódico", phonetic: "/pe.ˈrjo.ði.ko/", pos: "n.", gender: "m", cn: "報紙", example: "Leo el periódico cada mañana.", exampleCn: "我每天早上看報紙。" },
      { word: "elección", phonetic: "/e.lek.ˈθjon/", pos: "n.", gender: "f", cn: "選舉；選擇", example: "Las elecciones son el próximo mes.", exampleCn: "選舉在下個月舉行。" },
      { word: "policía", phonetic: "/po.li.ˈθi.a/", pos: "n.", gender: "f/m", cn: "警察；警察局", example: "La policía investiga el crimen.", exampleCn: "警方正在調查犯罪案件。" },
      { word: "hospital", phonetic: "/os.pi.ˈtal/", pos: "n.", gender: "m", cn: "醫院", example: "El nuevo hospital abrió la semana pasada.", exampleCn: "新醫院上週開業了。" },
      { word: "medio ambiente", phonetic: "/ˈme.ðjo am.ˈβjen.te/", pos: "n.", gender: "m", cn: "環境；自然環境", example: "Debemos proteger el medio ambiente.", exampleCn: "我們應該保護環境。" },
    ],
  },
};

export default spanishVocabData;
