const vocabData = {
  "學術教育": [
    { word: "curriculum", phonetic: "/kəˈrɪk.jʊ.ləm/", pos: "n.", cn: "課程", example: "The school revised its curriculum last year.", exampleCn: "學校去年修訂了課程。" },
    { word: "assignment", phonetic: "/əˈsaɪn.mənt/", pos: "n.", cn: "作業；任務", example: "Please submit your assignment by Friday.", exampleCn: "請在星期五前提交作業。" },
    { word: "evaluate", phonetic: "/ɪˈvæl.ju.eɪt/", pos: "v.", cn: "評估；評價", example: "Teachers evaluate students through exams and projects.", exampleCn: "教師透過考試和專題來評估學生。" },
    { word: "lecture", phonetic: "/ˈlek.tʃər/", pos: "n.", cn: "講課；演講", example: "The professor gave an interesting lecture on history.", exampleCn: "教授給了一堂關於歷史的有趣講課。" },
    { word: "semester", phonetic: "/sɪˈmes.tər/", pos: "n.", cn: "學期", example: "The new semester begins in September.", exampleCn: "新學期在九月開始。" },
    { word: "thesis", phonetic: "/ˈθiː.sɪs/", pos: "n.", cn: "論文", example: "She spent two years writing her thesis.", exampleCn: "她花了兩年時間撰寫論文。" },
    { word: "academic", phonetic: "/ˌæk.əˈdem.ɪk/", pos: "adj.", cn: "學術的", example: "He has an impressive academic record.", exampleCn: "他有出色的學業成績。" },
    { word: "discipline", phonetic: "/ˈdɪs.ɪ.plɪn/", pos: "n.", cn: "紀律；學科", example: "Science is a broad academic discipline.", exampleCn: "科學是一個廣泛的學術學科。" },
    { word: "faculty", phonetic: "/ˈfæk.əl.ti/", pos: "n.", cn: "院系；全體教職員", example: "The faculty members voted on the new policy.", exampleCn: "全體教職員對新政策進行了投票。" },
    { word: "graduate", phonetic: "/ˈɡræd.ju.ɪt/", pos: "v./n.", cn: "畢業；畢業生", example: "She will graduate from university next year.", exampleCn: "她明年將從大學畢業。" },
    { word: "literacy", phonetic: "/ˈlɪt.ər.ə.si/", pos: "n.", cn: "讀寫能力", example: "Improving literacy is a key education goal.", exampleCn: "提高讀寫能力是一個主要的教育目標。" },
    { word: "syllabus", phonetic: "/ˈsɪl.ə.bəs/", pos: "n.", cn: "教學大綱", example: "The syllabus outlines all topics for the course.", exampleCn: "教學大綱列出了課程的所有主題。" },
    { word: "tuition", phonetic: "/tjuːˈɪʃ.ən/", pos: "n.", cn: "學費；補習", example: "University tuition fees have increased significantly.", exampleCn: "大學學費大幅增加。" },
    { word: "scholarship", phonetic: "/ˈskɒl.ə.ʃɪp/", pos: "n.", cn: "獎學金", example: "He received a scholarship to study abroad.", exampleCn: "他獲得了出國留學的獎學金。" },
    { word: "comprehend", phonetic: "/ˌkɒm.prɪˈhend/", pos: "v.", cn: "理解；領會", example: "It can be hard to comprehend complex theories.", exampleCn: "要理解複雜的理論可能很困難。" },
  ],

  "科技": [
    { word: "algorithm", phonetic: "/ˈæl.ɡə.rɪ.ðəm/", pos: "n.", cn: "演算法", example: "The search engine uses a complex algorithm.", exampleCn: "搜尋引擎使用複雜的演算法。" },
    { word: "artificial", phonetic: "/ˌɑː.tɪˈfɪʃ.əl/", pos: "adj.", cn: "人工的；人造的", example: "Artificial intelligence is changing many industries.", exampleCn: "人工智能正在改變許多行業。" },
    { word: "bandwidth", phonetic: "/ˈbænd.wɪdθ/", pos: "n.", cn: "頻寬", example: "Streaming video requires a lot of bandwidth.", exampleCn: "串流視頻需要大量頻寬。" },
    { word: "database", phonetic: "/ˈdeɪ.tə.beɪs/", pos: "n.", cn: "資料庫", example: "The company stores customer data in a secure database.", exampleCn: "公司將客戶資料儲存在安全的資料庫中。" },
    { word: "digital", phonetic: "/ˈdɪdʒ.ɪ.təl/", pos: "adj.", cn: "數位的", example: "Digital technology has transformed communication.", exampleCn: "數位技術改變了通訊方式。" },
    { word: "encryption", phonetic: "/ɪnˈkrɪp.ʃən/", pos: "n.", cn: "加密", example: "Encryption protects your personal information online.", exampleCn: "加密保護你的個人網絡資料。" },
    { word: "innovation", phonetic: "/ˌɪn.əˈveɪ.ʃən/", pos: "n.", cn: "創新", example: "Innovation in technology improves daily life.", exampleCn: "科技創新改善了日常生活。" },
    { word: "interface", phonetic: "/ˈɪn.tə.feɪs/", pos: "n.", cn: "介面；介面", example: "The app has a user-friendly interface.", exampleCn: "這個應用程式有一個用戶友好的介面。" },
    { word: "network", phonetic: "/ˈnet.wɜːk/", pos: "n.", cn: "網絡", example: "Our office has a fast wireless network.", exampleCn: "我們辦公室有一個快速的無線網絡。" },
    { word: "software", phonetic: "/ˈsɒft.weər/", pos: "n.", cn: "軟件", example: "You need to update your software regularly.", exampleCn: "你需要定期更新軟件。" },
    { word: "virtual", phonetic: "/ˈvɜː.tʃu.əl/", pos: "adj.", cn: "虛擬的", example: "Virtual meetings have become common since the pandemic.", exampleCn: "自疫情以來，虛擬會議變得普遍。" },
    { word: "automation", phonetic: "/ˌɔː.təˈmeɪ.ʃən/", pos: "n.", cn: "自動化", example: "Automation has replaced many factory jobs.", exampleCn: "自動化取代了許多工廠工作。" },
    { word: "gadget", phonetic: "/ˈɡædʒ.ɪt/", pos: "n.", cn: "小器具；小工具", example: "He loves buying the latest gadgets.", exampleCn: "他喜歡購買最新的小工具。" },
    { word: "prototype", phonetic: "/ˈprəʊ.tə.taɪp/", pos: "n.", cn: "原型", example: "The engineers built a prototype of the new device.", exampleCn: "工程師建造了新裝置的原型。" },
    { word: "wireless", phonetic: "/ˈwaɪə.ləs/", pos: "adj.", cn: "無線的", example: "Wireless charging is now common in smartphones.", exampleCn: "無線充電現在在智能手機中很普遍。" },
  ],

  "環境": [
    { word: "biodiversity", phonetic: "/ˌbaɪ.əʊ.daɪˈvɜː.sɪ.ti/", pos: "n.", cn: "生物多樣性", example: "Rainforests are important for biodiversity.", exampleCn: "熱帶雨林對生物多樣性很重要。" },
    { word: "carbon", phonetic: "/ˈkɑː.bən/", pos: "n.", cn: "碳", example: "Cars release carbon dioxide into the atmosphere.", exampleCn: "汽車向大氣層釋放二氧化碳。" },
    { word: "climate", phonetic: "/ˈklaɪ.mɪt/", pos: "n.", cn: "氣候", example: "Climate change is a major global challenge.", exampleCn: "氣候變化是一個重大的全球挑戰。" },
    { word: "deforestation", phonetic: "/ˌdiː.fɒr.ɪˈsteɪ.ʃən/", pos: "n.", cn: "砍伐森林", example: "Deforestation destroys animal habitats.", exampleCn: "砍伐森林破壞了動物的棲息地。" },
    { word: "ecosystem", phonetic: "/ˈiː.kəʊ.sɪs.təm/", pos: "n.", cn: "生態系統", example: "The coral reef is a delicate ecosystem.", exampleCn: "珊瑚礁是一個脆弱的生態系統。" },
    { word: "emission", phonetic: "/ɪˈmɪʃ.ən/", pos: "n.", cn: "排放（物）", example: "Governments aim to reduce carbon emissions.", exampleCn: "各國政府致力於減少碳排放。" },
    { word: "extinction", phonetic: "/ɪkˈstɪŋk.ʃən/", pos: "n.", cn: "滅絕", example: "Many species face extinction due to habitat loss.", exampleCn: "許多物種因棲息地喪失而面臨滅絕。" },
    { word: "fossil", phonetic: "/ˈfɒs.əl/", pos: "n./adj.", cn: "化石；化石燃料的", example: "We must reduce our reliance on fossil fuels.", exampleCn: "我們必須減少對化石燃料的依賴。" },
    { word: "greenhouse", phonetic: "/ˈɡriːn.haʊs/", pos: "n./adj.", cn: "溫室；溫室效應的", example: "Greenhouse gases trap heat in the atmosphere.", exampleCn: "溫室氣體在大氣層中困住熱量。" },
    { word: "habitat", phonetic: "/ˈhæb.ɪ.tæt/", pos: "n.", cn: "棲息地", example: "Polar bears are losing their natural habitat.", exampleCn: "北極熊正在失去其自然棲息地。" },
    { word: "pollution", phonetic: "/pəˈluː.ʃən/", pos: "n.", cn: "污染", example: "Air pollution is a serious health risk in big cities.", exampleCn: "空氣污染在大城市是嚴重的健康風險。" },
    { word: "recycle", phonetic: "/ˌriːˈsaɪ.kəl/", pos: "v.", cn: "回收；循環再用", example: "We should recycle paper, glass, and plastic.", exampleCn: "我們應該回收紙張、玻璃和塑料。" },
    { word: "renewable", phonetic: "/rɪˈnjuː.ə.bəl/", pos: "adj.", cn: "可再生的", example: "Solar and wind are renewable energy sources.", exampleCn: "太陽能和風能是可再生能源。" },
    { word: "sustainable", phonetic: "/səˈsteɪ.nə.bəl/", pos: "adj.", cn: "可持續的", example: "Sustainable farming protects the environment.", exampleCn: "可持續農業保護環境。" },
    { word: "wildlife", phonetic: "/ˈwaɪld.laɪf/", pos: "n.", cn: "野生動植物", example: "National parks protect local wildlife.", exampleCn: "國家公園保護當地野生動植物。" },
  ],

  "健康": [
    { word: "antibiotic", phonetic: "/ˌæn.ti.baɪˈɒt.ɪk/", pos: "n.", cn: "抗生素", example: "The doctor prescribed antibiotics for the infection.", exampleCn: "醫生開了抗生素來治療感染。" },
    { word: "chronic", phonetic: "/ˈkrɒn.ɪk/", pos: "adj.", cn: "慢性的；長期的", example: "Chronic back pain affects millions of people.", exampleCn: "慢性背痛影響數以百萬計的人。" },
    { word: "diagnosis", phonetic: "/ˌdaɪ.əɡˈnəʊ.sɪs/", pos: "n.", cn: "診斷", example: "Early diagnosis of cancer improves survival rates.", exampleCn: "癌症的早期診斷提高了存活率。" },
    { word: "epidemic", phonetic: "/ˌep.ɪˈdem.ɪk/", pos: "n.", cn: "傳染病流行；疫情", example: "The flu epidemic affected millions of people.", exampleCn: "流感疫情影響了數百萬人。" },
    { word: "hygiene", phonetic: "/ˈhaɪ.dʒiːn/", pos: "n.", cn: "衛生；清潔", example: "Good hygiene helps prevent the spread of disease.", exampleCn: "良好的衛生有助於防止疾病傳播。" },
    { word: "immune", phonetic: "/ɪˈmjuːn/", pos: "adj.", cn: "免疫的", example: "Vaccines help the body become immune to diseases.", exampleCn: "疫苗幫助身體對疾病產生免疫力。" },
    { word: "infection", phonetic: "/ɪnˈfek.ʃən/", pos: "n.", cn: "感染", example: "Wash your hands to avoid infection.", exampleCn: "洗手以避免感染。" },
    { word: "nutrition", phonetic: "/njuːˈtrɪʃ.ən/", pos: "n.", cn: "營養", example: "Good nutrition is essential for children's growth.", exampleCn: "良好的營養對兒童成長至關重要。" },
    { word: "prescription", phonetic: "/prɪˈskrɪp.ʃən/", pos: "n.", cn: "處方；藥方", example: "You need a prescription to buy this medication.", exampleCn: "你需要處方才能購買這種藥物。" },
    { word: "symptom", phonetic: "/ˈsɪmp.təm/", pos: "n.", cn: "症狀", example: "Fever is a common symptom of the flu.", exampleCn: "發燒是流感的常見症狀。" },
    { word: "therapy", phonetic: "/ˈθer.ə.pi/", pos: "n.", cn: "治療；療法", example: "Physical therapy helped him recover from injury.", exampleCn: "物理治療幫助他從受傷中恢復。" },
    { word: "vaccination", phonetic: "/ˌvæk.sɪˈneɪ.ʃən/", pos: "n.", cn: "接種疫苗", example: "Vaccination is the best way to prevent measles.", exampleCn: "接種疫苗是預防麻疹的最佳方法。" },
    { word: "obesity", phonetic: "/əʊˈbiː.sɪ.ti/", pos: "n.", cn: "肥胖症", example: "Obesity increases the risk of heart disease.", exampleCn: "肥胖症增加了患心臟病的風險。" },
    { word: "mental", phonetic: "/ˈmen.təl/", pos: "adj.", cn: "精神的；心理的", example: "Mental health is just as important as physical health.", exampleCn: "心理健康與身體健康同樣重要。" },
    { word: "surgery", phonetic: "/ˈsɜː.dʒər.i/", pos: "n.", cn: "外科手術", example: "He underwent surgery to remove the tumour.", exampleCn: "他接受了切除腫瘤的外科手術。" },
  ],

  "商業經濟": [
    { word: "budget", phonetic: "/ˈbʌdʒ.ɪt/", pos: "n.", cn: "預算", example: "The project was completed within budget.", exampleCn: "該項目在預算內完成。" },
    { word: "consumer", phonetic: "/kənˈsjuː.mər/", pos: "n.", cn: "消費者", example: "Consumers are spending less during the recession.", exampleCn: "消費者在經濟衰退期間減少了支出。" },
    { word: "contract", phonetic: "/ˈkɒn.trækt/", pos: "n.", cn: "合約；合同", example: "Both parties signed the contract.", exampleCn: "雙方簽署了合約。" },
    { word: "corporation", phonetic: "/ˌkɔː.pərˈeɪ.ʃən/", pos: "n.", cn: "公司；企業", example: "The corporation has offices in 30 countries.", exampleCn: "該公司在30個國家設有辦事處。" },
    { word: "economy", phonetic: "/ɪˈkɒn.ə.mi/", pos: "n.", cn: "經濟；經濟體", example: "The economy grew by 3% last year.", exampleCn: "去年經濟增長了3%。" },
    { word: "export", phonetic: "/ˈek.spɔːt/", pos: "v./n.", cn: "出口；輸出", example: "China exports goods to countries worldwide.", exampleCn: "中國向全球各國出口商品。" },
    { word: "inflation", phonetic: "/ɪnˈfleɪ.ʃən/", pos: "n.", cn: "通貨膨脹", example: "High inflation makes everyday goods more expensive.", exampleCn: "高通膨使日常商品更加昂貴。" },
    { word: "investment", phonetic: "/ɪnˈvest.mənt/", pos: "n.", cn: "投資", example: "Property is a popular long-term investment.", exampleCn: "房地產是一種受歡迎的長期投資。" },
    { word: "marketing", phonetic: "/ˈmɑː.kɪ.tɪŋ/", pos: "n.", cn: "市場營銷", example: "Effective marketing can boost sales significantly.", exampleCn: "有效的市場營銷可以大幅提升銷售額。" },
    { word: "negotiate", phonetic: "/nɪˈɡəʊ.ʃi.eɪt/", pos: "v.", cn: "談判；協商", example: "They negotiated a better deal with the supplier.", exampleCn: "他們與供應商談判達成了更好的交易。" },
    { word: "profit", phonetic: "/ˈprɒf.ɪt/", pos: "n.", cn: "利潤；盈利", example: "The company made a large profit this quarter.", exampleCn: "公司本季度獲得了豐厚利潤。" },
    { word: "revenue", phonetic: "/ˈrev.ɪ.njuː/", pos: "n.", cn: "收入；收益", example: "The government's tax revenue increased last year.", exampleCn: "政府去年的稅收增加了。" },
    { word: "enterprise", phonetic: "/ˈen.tə.praɪz/", pos: "n.", cn: "企業；事業", example: "Small enterprises are the backbone of the economy.", exampleCn: "小型企業是經濟的支柱。" },
    { word: "strategy", phonetic: "/ˈstræt.ɪ.dʒi/", pos: "n.", cn: "策略；戰略", example: "The company developed a new marketing strategy.", exampleCn: "公司制定了新的市場策略。" },
    { word: "competitor", phonetic: "/kəmˈpet.ɪ.tər/", pos: "n.", cn: "競爭對手", example: "They lowered prices to beat their competitors.", exampleCn: "他們降低價格以擊敗競爭對手。" },
  ],

  "社會": [
    { word: "community", phonetic: "/kəˈmjuː.nɪ.ti/", pos: "n.", cn: "社區；社群", example: "The community came together to help flood victims.", exampleCn: "社區齊心協力幫助洪水災民。" },
    { word: "diversity", phonetic: "/daɪˈvɜː.sɪ.ti/", pos: "n.", cn: "多元化；多樣性", example: "Our school celebrates cultural diversity.", exampleCn: "我們的學校慶祝文化多樣性。" },
    { word: "equality", phonetic: "/ɪˈkwɒl.ɪ.ti/", pos: "n.", cn: "平等", example: "Many people fight for gender equality.", exampleCn: "很多人為性別平等而奮鬥。" },
    { word: "freedom", phonetic: "/ˈfriː.dəm/", pos: "n.", cn: "自由", example: "Freedom of speech is a fundamental right.", exampleCn: "言論自由是一項基本權利。" },
    { word: "justice", phonetic: "/ˈdʒʌs.tɪs/", pos: "n.", cn: "公正；司法", example: "The protesters demanded justice for the victims.", exampleCn: "抗議者要求為受害者伸張正義。" },
    { word: "poverty", phonetic: "/ˈpɒv.ə.ti/", pos: "n.", cn: "貧困；貧窮", example: "Many charities work to reduce global poverty.", exampleCn: "許多慈善機構致力於減少全球貧困。" },
    { word: "prejudice", phonetic: "/ˈpredʒ.ʊ.dɪs/", pos: "n.", cn: "偏見；歧視", example: "We must work to overcome racial prejudice.", exampleCn: "我們必須努力克服種族偏見。" },
    { word: "protest", phonetic: "/ˈprəʊ.test/", pos: "n./v.", cn: "抗議", example: "Thousands joined the protest against the new law.", exampleCn: "數千人加入了反對新法律的抗議。" },
    { word: "refugee", phonetic: "/ˌref.jʊˈdʒiː/", pos: "n.", cn: "難民", example: "The country accepted thousands of refugees.", exampleCn: "該國接收了數千名難民。" },
    { word: "tradition", phonetic: "/trəˈdɪʃ.ən/", pos: "n.", cn: "傳統", example: "This festival is an important local tradition.", exampleCn: "這個節日是一個重要的本地傳統。" },
    { word: "welfare", phonetic: "/ˈwel.feər/", pos: "n.", cn: "福利；幸福", example: "The government increased social welfare payments.", exampleCn: "政府增加了社會福利金。" },
    { word: "volunteer", phonetic: "/ˌvɒl.ənˈtɪər/", pos: "n./v.", cn: "義工；自願做", example: "Many people volunteer at local food banks.", exampleCn: "很多人在本地食物銀行做義工。" },
    { word: "minority", phonetic: "/maɪˈnɒr.ɪ.ti/", pos: "n.", cn: "少數族裔；少數群體", example: "The law protects the rights of minorities.", exampleCn: "法律保護少數群體的權利。" },
    { word: "urban", phonetic: "/ˈɜː.bən/", pos: "adj.", cn: "城市的；都市的", example: "Urban areas often have better access to services.", exampleCn: "城市地區通常能更方便地獲取服務。" },
    { word: "discrimination", phonetic: "/dɪˌskrɪm.ɪˈneɪ.ʃən/", pos: "n.", cn: "歧視", example: "Discrimination in the workplace is illegal.", exampleCn: "職場歧視是違法的。" },
  ],

  "文化": [
    { word: "architecture", phonetic: "/ˈɑː.kɪ.tek.tʃər/", pos: "n.", cn: "建築；建築學", example: "The city is famous for its Gothic architecture.", exampleCn: "這座城市以其哥特式建築而聞名。" },
    { word: "ceremony", phonetic: "/ˈser.ɪ.mə.ni/", pos: "n.", cn: "儀式；典禮", example: "The opening ceremony attracted millions of viewers.", exampleCn: "開幕式吸引了數百萬名觀眾。" },
    { word: "dialect", phonetic: "/ˈdaɪ.ə.lekt/", pos: "n.", cn: "方言", example: "Many dialects are spoken in southern China.", exampleCn: "中國南方有許多方言。" },
    { word: "ethnic", phonetic: "/ˈeθ.nɪk/", pos: "adj.", cn: "民族的；種族的", example: "The city has many ethnic restaurants.", exampleCn: "這座城市有許多民族餐廳。" },
    { word: "folklore", phonetic: "/ˈfəʊk.lɔːr/", pos: "n.", cn: "民間傳說；民俗", example: "The story comes from local folklore.", exampleCn: "這個故事來自當地民間傳說。" },
    { word: "heritage", phonetic: "/ˈher.ɪ.tɪdʒ/", pos: "n.", cn: "文化遺產；遺產", example: "The ancient temple is a UNESCO World Heritage site.", exampleCn: "這座古廟是聯合國教科文組織的世界遺產。" },
    { word: "legend", phonetic: "/ˈledʒ.ənd/", pos: "n.", cn: "傳說；傳奇人物", example: "The legend of the dragon is common in Asia.", exampleCn: "龍的傳說在亞洲很普遍。" },
    { word: "mythology", phonetic: "/mɪˈθɒl.ə.dʒi/", pos: "n.", cn: "神話", example: "Greek mythology features many gods and heroes.", exampleCn: "希臘神話有許多神明和英雄。" },
    { word: "sculpture", phonetic: "/ˈskʌlp.tʃər/", pos: "n.", cn: "雕塑；雕刻", example: "The museum has a large collection of sculptures.", exampleCn: "博物館收藏了大量雕塑。" },
    { word: "symbol", phonetic: "/ˈsɪm.bəl/", pos: "n.", cn: "象徵；符號", example: "The dove is a symbol of peace.", exampleCn: "鴿子是和平的象徵。" },
    { word: "literature", phonetic: "/ˈlɪt.ər.ɪ.tʃər/", pos: "n.", cn: "文學", example: "She studied English literature at university.", exampleCn: "她在大學學習英國文學。" },
    { word: "festival", phonetic: "/ˈfes.tɪ.vəl/", pos: "n.", cn: "節日；節慶", example: "The Lunar New Year festival is celebrated worldwide.", exampleCn: "農曆新年節日在世界各地慶祝。" },
    { word: "cuisine", phonetic: "/kwɪˈziːn/", pos: "n.", cn: "烹飪；料理", example: "Japanese cuisine is known for its fresh ingredients.", exampleCn: "日本料理以新鮮食材著稱。" },
    { word: "artifact", phonetic: "/ˈɑː.tɪ.fækt/", pos: "n.", cn: "文物；人工製品", example: "The museum displays ancient artifacts from Egypt.", exampleCn: "博物館展示來自埃及的古代文物。" },
    { word: "indigenous", phonetic: "/ɪnˈdɪdʒ.ɪ.nəs/", pos: "adj.", cn: "土著的；原住民的", example: "Indigenous peoples have lived here for centuries.", exampleCn: "原住民在這裡已經生活了幾個世紀。" },
  ],

  "政治": [
    { word: "authority", phonetic: "/ɔːˈθɒr.ɪ.ti/", pos: "n.", cn: "權威；當局", example: "The police have the authority to arrest suspects.", exampleCn: "警察有逮捕嫌疑人的權力。" },
    { word: "campaign", phonetic: "/kæmˈpeɪn/", pos: "n./v.", cn: "競選；活動", example: "The candidate ran a successful election campaign.", exampleCn: "候選人進行了一場成功的選舉競選。" },
    { word: "citizen", phonetic: "/ˈsɪt.ɪ.zən/", pos: "n.", cn: "公民", example: "Every citizen has the right to vote.", exampleCn: "每個公民都有投票的權利。" },
    { word: "constitution", phonetic: "/ˌkɒn.stɪˈtjuː.ʃən/", pos: "n.", cn: "憲法", example: "The constitution protects basic human rights.", exampleCn: "憲法保護基本人權。" },
    { word: "debate", phonetic: "/dɪˈbeɪt/", pos: "n./v.", cn: "辯論；討論", example: "Politicians debated the new tax policy.", exampleCn: "政治家們就新的稅收政策進行了辯論。" },
    { word: "democracy", phonetic: "/dɪˈmɒk.rə.si/", pos: "n.", cn: "民主；民主制度", example: "Democracy gives citizens a voice in government.", exampleCn: "民主制度讓公民在政府中有發言權。" },
    { word: "diplomatic", phonetic: "/ˌdɪp.ləˈmæt.ɪk/", pos: "adj.", cn: "外交的", example: "The two countries have strong diplomatic ties.", exampleCn: "兩國擁有緊密的外交關係。" },
    { word: "election", phonetic: "/ɪˈlek.ʃən/", pos: "n.", cn: "選舉", example: "The general election will be held in November.", exampleCn: "大選將於11月舉行。" },
    { word: "govern", phonetic: "/ˈɡʌv.ən/", pos: "v.", cn: "統治；管理", example: "The prime minister governs the country.", exampleCn: "首相治理這個國家。" },
    { word: "minister", phonetic: "/ˈmɪn.ɪ.stər/", pos: "n.", cn: "部長；大臣", example: "The Finance Minister announced new tax cuts.", exampleCn: "財政部長宣布了新的減稅措施。" },
    { word: "parliament", phonetic: "/ˈpɑː.lə.mənt/", pos: "n.", cn: "議會；國會", example: "The new law was passed by parliament.", exampleCn: "新法律獲得議會通過。" },
    { word: "policy", phonetic: "/ˈpɒl.ɪ.si/", pos: "n.", cn: "政策", example: "The government introduced a new housing policy.", exampleCn: "政府推出了新的房屋政策。" },
    { word: "republic", phonetic: "/rɪˈpʌb.lɪk/", pos: "n.", cn: "共和國", example: "France is a republic with an elected president.", exampleCn: "法國是一個有民選總統的共和國。" },
    { word: "sanction", phonetic: "/ˈsæŋk.ʃən/", pos: "n./v.", cn: "制裁；批准", example: "The UN imposed sanctions on the country.", exampleCn: "聯合國對該國實施了制裁。" },
    { word: "treaty", phonetic: "/ˈtriː.ti/", pos: "n.", cn: "條約；協議", example: "The two nations signed a peace treaty.", exampleCn: "兩國簽署了和平條約。" },
  ],
};

export default vocabData;
